# Generated by Django 5.0.3 on 2024-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Normale'), (4, 'Élevée'), (5, 'Trés Elevée')], max_length=100),
        ),
    ]
